<?php

namespace Native\HelloBundle\Entity;


/**
 * utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateurRepository extends \Doctrine\ORM\EntityRepository {

//    public function Search($queryString,$queryString2) {

//        $qb = $this->createQueryBuilder('u')  //add select and array for JSON
//                ->where('u.content LIKE :string OR u.content LIKE :string2')
//                ->setParameter("string", "%" . $queryString . "%")
//                ->setParameter("string2", "%" . $queryString2 . "%")
//                ->setMaxResults('10');

//        return $qb->getQuery()
//                        ->getResult();
//    }

}
